.gitignore, build.gradle, src/main/resources/application.properties
https://www.notion.so/nyunglog/753a3f31d256441b8e056116b58e47ff
프로젝트 설정 파일 정리한 페이지 입니다. 참고 부탁드립니다.
close #3
=> 3 chore 프로젝트 기본 설정

src/main/java/com/sparta/gamjaquick/category/entity/Category.java, src/main/java/com/sparta/gamjaquick/category/repository/CategoryRepository.java, src/main/java/com/sparta/gamjaquick/common/AuditingFields.java
category entity 및 auditing 클래스 추가
close #6
=> category entity 및 auditing 클래스 추가

src/main/java/com/sparta/gamjaquick/order/entity/Order.java, src/main/java/com/sparta/gamjaquick/orderItem/entity/OrderItem.java, src/main/java/com/sparta/gamjaquick/payment/entity/Payment.java
=> ✨feat : order, order item, payment entity 생성

src/main/java/com/sparta/gamjaquick/common/AuditingFields.java, src/main/java/com/sparta/gamjaquick/menu/controller/MenuController.java, src/main/java/com/sparta/gamjaquick/menu/dto/request/MenuRequestDto.java, src/main/java/com/sparta/gamjaquick/menu/dto/response/MenuResponseDto.java, src/main/java/com/sparta/gamjaquick/menu/entity/Menu.java, src/main/java/com/sparta/gamjaquick/menu/repository/MenuRepository.java, src/main/java/com/sparta/gamjaquick/menu/service/MenuService.java
menu entity 생성 및 controller , service 로직 임시 구성
=> ✨feat : menu entity 생성 및 controller , service 로직 임시 구성 

src/main/java/com/sparta/gamjaquick/user/entity/User.java, src/main/java/com/sparta/gamjaquick/user/repository/UserRepository.java
=> ✨feat : user entity 생성

src/main/java/com/sparta/gamjaquick/GamjaQuickApplication.java, src/main/java/com/sparta/gamjaquick/category/entity/Category.java, src/main/java/com/sparta/gamjaquick/common/response/ApiResponseDto.java, src/main/java/com/sparta/gamjaquick/common/response/ErrorResponseDto.java, src/main/java/com/sparta/gamjaquick/common/response/MessageType.java, src/main/java/com/sparta/gamjaquick/global/error/ErrorCode.java, src/main/java/com/sparta/gamjaquick/global/error/GlobalExceptionHandler.java, src/main/java/com/sparta/gamjaquick/global/error/exception/BusinessException.java
공통 응답 코드 및 에러 핸들링 추가
관련 내용 노션에 정리했습니다. 참고 부탁드립니다!
https://www.notion.so/nyunglog/c4c83b2a41794db8aa250df801cfdf4a
close #8
=> ✨feat : 공통 응답 코드 및 에러 핸들링 추가

src/main/java/com/sparta/gamjaquick/common/AuditingFields.java, src/main/java/com/sparta/gamjaquick/menu/controller/MenuController.java, src/main/java/com/sparta/gamjaquick/menu/entity/Menu.java, src/main/java/com/sparta/gamjaquick/menu/repository/MenuRepository.java, src/main/java/com/sparta/gamjaquick/menu/service/MenuService.java
feat: 기존 code 수정 및 sevice 로직 구현
service 로직을 조금 수정 해보았는데 아직 완성은 아니라 배송지 entity 먼저 만든 후 다른 분들 코드 완성 되면 좀 더 수정하고 맞출 예정입니다.
=> ✨feat: 기존 code 수정 및 sevice 로직 구현

.gitignore, build.gradle, src/main/java/com/sparta/gamjaquick/GamjaQuickApplication.java, src/main/java/com/sparta/gamjaquick/category/dto/response/CategoryResponseDto.java, src/main/java/com/sparta/gamjaquick/category/repository/CategoryRepository.java, src/main/java/com/sparta/gamjaquick/category/repository/CategoryRepositoryCustom.java, src/main/java/com/sparta/gamjaquick/category/repository/CategoryRepositoryImpl.java, src/main/java/com/sparta/gamjaquick/category/service/CategoryService.java, src/main/java/com/sparta/gamjaquick/common/request/SearchParameter.java, src/main/java/com/sparta/gamjaquick/common/response/PageResponseDto.java, src/main/java/com/sparta/gamjaquick/config/jpa/JpaConfig.java
- 공통 검색 형식 추가
- 공통 페이지 응답 형식 추가
관련 노션 정리
https://www.notion.so/nyunglog/fc0fed65db214e96b47ab17fb85eba9b
close #19
=> ✨feat : 공통 검색 형식 및 페이지 응답 형식 추가

build.gradle, src/main/java/com/sparta/gamjaquick/user/dto/request/UserLoginRequestDto.java, src/main/java/com/sparta/gamjaquick/user/dto/request/UserSignUpRequestDto.java, src/main/java/com/sparta/gamjaquick/user/dto/request/UserUpdateRequestDto.java, src/main/java/com/sparta/gamjaquick/user/dto/response/UserDeleteResponseDto.java, src/main/java/com/sparta/gamjaquick/user/dto/response/UserResponseDto.java
DTO를 늦게 올리게 되었습니다!!! 여러모로 문제가 발생했었네요...
gradle 빌드 문제, 깃허브 인증 문제, 클래스 import 안됨을 뚫고 달려왔읍니다 ^__^
=> ✨feat: UserDTO 작성

src/main/java/com/sparta/gamjaquick/user/repository/UserRepository.java
User Repository 코드를 작성 완료하였습니다
=> ✨feat: User repository

build.gradle, src/main/java/com/sparta/gamjaquick/category/controller/CategoryController.java, src/main/java/com/sparta/gamjaquick/category/dto/request/CategoryRequestDto.java, src/main/java/com/sparta/gamjaquick/category/entity/Category.java, src/main/java/com/sparta/gamjaquick/category/repository/CategoryRepository.java, src/main/java/com/sparta/gamjaquick/category/repository/CategoryRepositoryImpl.java, src/main/java/com/sparta/gamjaquick/category/service/CategoryService.java, src/main/java/com/sparta/gamjaquick/common/AuditingFields.java, src/main/java/com/sparta/gamjaquick/common/response/ApiResponseDto.java, src/main/java/com/sparta/gamjaquick/config/jpa/JpaConfig.java, src/main/java/com/sparta/gamjaquick/global/error/ErrorCode.java
뭔가 커밋이 중복이 된 것 같슴다..
- category 관련 CRUD 기능 추가
- 자동으로 생성자, 수정자, 삭제자 등록하는 로직 추가
close #17
=> ✨feat : category 관련 api 개발

src/main/java/com/sparta/gamjaquick/category/dto/request/CategoryRequestDto.java, src/main/java/com/sparta/gamjaquick/category/entity/Category.java, src/main/java/com/sparta/gamjaquick/store/entity/Store.java, src/main/java/com/sparta/gamjaquick/store/entity/StoreStatus.java, src/main/java/com/sparta/gamjaquick/store/repository/StoreRepository.java
store entity 및 repository 추가했습니다.
요구사항 중
- 운영 지역
- **지역:** 초기에는 광화문 근처로 한정하여 운영하며, 향후 확장을 고려한 지역 분류 시스템 설계 필요
- ***향후 확장성**: 지역별 필터링, 지역정보 수정 및 추가 등이 가능 하도록 고려*
관련해서 추가 작업 후 말씀드리겠습니다!
=> ✨feat: store entity 추가

src/main/java/com/sparta/gamjaquick/order/dto/request/OrderCreateRequestDto.java, src/main/java/com/sparta/gamjaquick/order/entity/DeliveryInfo.java, src/main/java/com/sparta/gamjaquick/order/repository/DeliveryInfoRepository.java
병민님 코드 많이 참고하여 entity에 삭제 수정 코드까지 추가해보았습니당 
다른 바꿀 사항있으면 얘기부탁드립니다
=> ✨feat: deliveryInfo entity&repository 작성

build.gradle, src/main/java/com/sparta/gamjaquick/user/controller/UserController.java, src/main/java/com/sparta/gamjaquick/user/entity/User.java, src/main/java/com/sparta/gamjaquick/user/repository/UserRepository.java, src/main/java/com/sparta/gamjaquick/user/service/UserService.java, src/main/java/com/sparta/gamjaquick/user/service/UserServiceImpl.java
- UserService 인터페이스와 UserServiceImpl 구현 클래스를 작성 완료하였습니다.
- 추가적인 검증이나 유효성 검사는 아직 추가 되지 않은 상태입니다.
- User Entity에 Setter 어노테이션이 빠져있어 추가하였습니다,
- 팀장님께서 User Entity PR 때 validation이 gradle에 중복으로 들어가있다고 알려주신 부분을 삭제하였습니다.
=> ✨feat: User Service, Controller 기능 작성 완료

src/main/java/com/sparta/gamjaquick/payment/dto/request/PaymentCancelRequestDto.java, src/main/java/com/sparta/gamjaquick/payment/dto/request/PaymentCreateRequestDto.java, src/main/java/com/sparta/gamjaquick/payment/dto/response/PaymentResponseDto.java, src/main/java/com/sparta/gamjaquick/payment/entity/Payment.java, src/main/java/com/sparta/gamjaquick/payment/entity/PaymentStatus.java, src/main/java/com/sparta/gamjaquick/payment/repository/PaymentRepository.java
payment dto, repository작성, entity의 enum클래스 분리했습니다
=> ✨feat : payment dto, repository작성, entity의 enum클래스 분리

src/main/java/com/sparta/gamjaquick/review/entity/Review.java
=> ✨feat: Review Entity

src/main/java/com/sparta/gamjaquick/review/dto/request/ReviewRequestDto.java, src/main/java/com/sparta/gamjaquick/review/dto/response/ReviewResponseDto.java, src/main/java/com/sparta/gamjaquick/review/repository/ReviewRepository.java
Review Dto와 Repository를 작성완료하였습니다.
Controller와 Service 작성 후 전반적인 테스트나 추후 Spring Security 추가 내용은 11/14에 데일리 스크럼 이후에 진행하도록 하겠습니다!
=> ✨feat: Review Dto & Repository

src/main/java/com/sparta/gamjaquick/review/controller/ReviewController.java, src/main/java/com/sparta/gamjaquick/review/dto/request/ReviewRequestDto.java, src/main/java/com/sparta/gamjaquick/review/dto/response/ReviewResponseDto.java, src/main/java/com/sparta/gamjaquick/review/repository/ReviewRepository.java, src/main/java/com/sparta/gamjaquick/review/service/ReviewService.java, src/main/java/com/sparta/gamjaquick/review/service/ReviewServiceImpl.java
storeID의 UUID를 가져오는 방식이 맞는지 [코드](https://github.com/JellyfishEgg/gamja-quick/blob/0deac711cc9ff9b4ca014120641a9cc7ce3a8de0/src/main/java/com/sparta/gamjaquick/review/service/ReviewServiceImpl.java#L42)에서 확인해주시면 정말 감사하겠습니다!
여기까지 User와 Review MVP 완성하였고 이제 시큐리티 하면서 다시 하나씩 보완해나가보겠습니다! 제가 10시 전에 일어나길 빌어주세요
=> ✨feat : Review Controller & Service 작성 완료

src/main/java/com/sparta/gamjaquick/menu/controller/MenuController.java, src/main/java/com/sparta/gamjaquick/menu/dto/request/MenuRequestDto.java, src/main/java/com/sparta/gamjaquick/menu/dto/response/MenuResponseDto.java, src/main/java/com/sparta/gamjaquick/menu/entity/Menu.java, src/main/java/com/sparta/gamjaquick/menu/repository/MenuRepository.java, src/main/java/com/sparta/gamjaquick/menu/service/MenuService.java
menu 검색 & 페이징 로직 추가
자잘한 코드 수정
모두의 코드를 조금씩 참고하여 수정해보았습니다.. 항상 감사합니다
=> ✨feat : menu 검색 & 페이징 로직 추가와 코드 수정

src/main/java/com/sparta/gamjaquick/global/error/ErrorCode.java, src/main/java/com/sparta/gamjaquick/review/entity/Review.java, src/main/java/com/sparta/gamjaquick/review/repository/ReviewRepository.java, src/main/java/com/sparta/gamjaquick/review/service/ReviewServiceImpl.java, src/main/java/com/sparta/gamjaquick/store/controller/StoreController.java, src/main/java/com/sparta/gamjaquick/store/dto/request/StoreCreateRequestDto.java, src/main/java/com/sparta/gamjaquick/store/dto/request/StoreUpdateRequestDto.java, src/main/java/com/sparta/gamjaquick/store/dto/response/StoreWithMenusResponseDto.java, src/main/java/com/sparta/gamjaquick/store/entity/Region.java, src/main/java/com/sparta/gamjaquick/store/entity/Store.java, src/main/java/com/sparta/gamjaquick/store/repository/StoreRepository.java, src/main/java/com/sparta/gamjaquick/store/repository/StoreRepositoryCustom.java, src/main/java/com/sparta/gamjaquick/store/repository/StoreRepositoryImpl.java, src/main/java/com/sparta/gamjaquick/store/service/StoreService.java, src/main/resources/data.sql
=> ✨feat: store crud 기능 추가

build.gradle, src/main/java/com/sparta/gamjaquick/airequestlog/entity/AiRequestLog.java, src/main/java/com/sparta/gamjaquick/airequestlog/repository/AiRequestLogRepository.java, src/main/java/com/sparta/gamjaquick/airequestlog/service/AiRequestLogService.java, src/main/java/com/sparta/gamjaquick/config/web/ObjectMapperConfig.java, src/main/java/com/sparta/gamjaquick/config/web/RestTemplateConfig.java, src/main/java/com/sparta/gamjaquick/global/error/ErrorCode.java, src/main/java/com/sparta/gamjaquick/global/util/JsonConvertUtil.java, src/main/java/com/sparta/gamjaquick/infra/ai/client/AiApiClient.java, src/main/java/com/sparta/gamjaquick/infra/ai/client/GoogleAiApiClient.java, src/main/java/com/sparta/gamjaquick/infra/ai/config/ApiConfig.java, src/main/java/com/sparta/gamjaquick/infra/ai/dto/AiApiRequestDto.java, src/main/java/com/sparta/gamjaquick/infra/ai/dto/AiApiResponseDto.java, src/main/java/com/sparta/gamjaquick/infra/ai/service/AiApiService.java, src/main/java/com/sparta/gamjaquick/menu/controller/MenuController.java, src/main/java/com/sparta/gamjaquick/menu/dto/request/ContentRequestDto.java, src/main/java/com/sparta/gamjaquick/menu/dto/response/ContentResponseDto.java, src/main/java/com/sparta/gamjaquick/menu/service/MenuService.java, src/main/java/com/sparta/gamjaquick/store/entity/Store.java
Google Ai API 연동하는 서비스 로직 완료했습니다. 로그 저장하는 작업도 진행하겠습니다!
=> ✨feat: ai api 연동

src/main/java/com/sparta/gamjaquick/review/entity/Review.java, src/main/java/com/sparta/gamjaquick/user/controller/UserController.java, src/main/java/com/sparta/gamjaquick/user/dto/request/UserSearchParameter.java, src/main/java/com/sparta/gamjaquick/user/entity/RoleType.java, src/main/java/com/sparta/gamjaquick/user/entity/User.java, src/main/java/com/sparta/gamjaquick/user/repository/UserRepository.java, src/main/java/com/sparta/gamjaquick/user/service/UserService.java, src/main/java/com/sparta/gamjaquick/user/service/UserServiceImpl.java
페이징 처리 추가 하면서 접근권한을 검색에만 적용이 됐습니다.
나머지 부분도 권한 관리 추가해서 올리겠습니다
=> ✨feat: User 페이징 처리 추가 

src/main/java/com/sparta/gamjaquick/user/controller/UserController.java, src/main/java/com/sparta/gamjaquick/user/dto/request/UserSignUpRequestDto.java, src/main/java/com/sparta/gamjaquick/user/dto/request/UserUpdateRequestDto.java, src/main/java/com/sparta/gamjaquick/user/entity/User.java, src/main/java/com/sparta/gamjaquick/user/service/UserServiceImpl.java
> User 도메인의 기본적인 기능과 Security를 이용한 역할 기반 권한 부여가 모두 완료 되었고 아래는 수정된 사항입니다. 
1. `UserController`
- 공통응답형식을 기반으로 Controller를 수정하였음
- 각 역할에 대한 주석을 좀 더 상사하게 달았음
- Javadoc 주석 스타일로 작성하였음
- 권한별로 접근 제어 빠진부분 추가하였음
- 사용자 조회, 삭제 : admin, customer, owner
- 사용자 목록 조회, 검색 : admin
- 사용자 수정 : customer, owner
1. `UserSignUpRequestDto`
- username과 password에 유효성 검증 조건이 빠져있어 추가하였음
1. `UserUpdateRequestDto`
- email 필드에 유효성 검증 조건이 빠져있어 추가하였음
1. `UserEntity`
- 생성자에서 매개변수와 필드 간의 매핑이 빠져서 추가하였음.
- username, password 등등등.. 유효성 검증 빠진 부분 추가하였음
- Object 타입 제거
- 계속 수정해왔던 부분이라 더 추가나 삭제할 부분은 없음
- findByUsernameContainingOrEmailContainingOrPhoneNumberContaining으로 조건부 검색 + 페이징
- UserServiceImpl에서 페이징 추가 때 발생했던 에러들을 마구잡이로 고치다보니 필요없는 것들이 import 된 부분 삭제하였음
- controller와 같은 형식으로 주석을 추가하였음
- `@RequiredArgsConstructor`를 추가하여 생성자 …
=> 🛠 chore : User 기본 기능 및 권한 부여 완성

src/main/java/com/sparta/gamjaquick/user/controller/UserController.java
=> ✨feat : user controller 스웨거 어노테이션 추가

src/main/java/com/sparta/gamjaquick/order/dto/request/OrderCreateRequestDto.java, src/main/java/com/sparta/gamjaquick/order/entity/Order.java
=> 🛠chore: order 수정

src/main/java/com/sparta/gamjaquick/config/security/jwt/JwtProperties.java, src/main/java/com/sparta/gamjaquick/config/security/jwt/JwtProvider.java, src/main/java/com/sparta/gamjaquick/user/controller/UserController.java, src/main/java/com/sparta/gamjaquick/user/dto/response/UserLoginResponseDto.java, src/main/java/com/sparta/gamjaquick/user/service/UserService.java, src/main/java/com/sparta/gamjaquick/user/service/UserServiceImpl.java
=> ✨feat : 로그인 API 구현 및 JWT 연동

src/main/java/com/sparta/gamjaquick/user/controller/UserController.java, src/main/java/com/sparta/gamjaquick/user/repository/UserRepository.java, src/main/java/com/sparta/gamjaquick/user/service/UserService.java, src/main/java/com/sparta/gamjaquick/user/service/UserServiceImpl.java
=> ✨feat : 사용자 정보 수정 및 삭제 기능에 JWT 연동 보강 + 로그아웃 기능 추가

src/main/java/com/sparta/gamjaquick/config/jpa/JpaConfig.java, src/main/java/com/sparta/gamjaquick/config/security/SecurityConfig.java, src/main/java/com/sparta/gamjaquick/global/error/ErrorCode.java, src/main/java/com/sparta/gamjaquick/health/controller/HealthCheckController.java, src/main/java/com/sparta/gamjaquick/health/dto/HealthCheckResponseDto.java, src/main/java/com/sparta/gamjaquick/infra/aws/provider/S3FileUploader.java, src/main/java/com/sparta/gamjaquick/orderItem/entity/OrderItem.java, src/main/java/com/sparta/gamjaquick/store/controller/StoreController.java, src/main/java/com/sparta/gamjaquick/store/entity/Store.java, src/main/java/com/sparta/gamjaquick/store/service/StoreService.java
=> ✨feat: 배포를 위한 코드 추가

src/main/java/com/sparta/gamjaquick/config/security/SecurityConfig.java, src/main/java/com/sparta/gamjaquick/global/error/ErrorCode.java, src/main/java/com/sparta/gamjaquick/menu/controller/MenuController.java, src/main/java/com/sparta/gamjaquick/store/controller/StoreController.java, src/main/java/com/sparta/gamjaquick/user/controller/UserController.java, src/main/java/com/sparta/gamjaquick/user/service/UserServiceImpl.java
=> 🛠️chore : 전체적인 api 테스트 코드 수정

src/main/java/com/sparta/gamjaquick/order/controller/OrderController.java, src/main/java/com/sparta/gamjaquick/order/dto/request/OrderStatusUpdateRequestDto.java, src/main/java/com/sparta/gamjaquick/order/dto/response/OrderResponseDto.java, src/main/java/com/sparta/gamjaquick/order/entity/Order.java, src/main/java/com/sparta/gamjaquick/order/repository/OrderRepository.java, src/main/java/com/sparta/gamjaquick/order/repository/OrderRepositoryCustom.java, src/main/java/com/sparta/gamjaquick/order/repository/OrderRepositoryImpl.java, src/main/java/com/sparta/gamjaquick/order/service/OrderService.java, src/main/java/com/sparta/gamjaquick/orderItem/dto/response/OrderItemResponseDto.java, src/main/java/com/sparta/gamjaquick/orderItem/entity/OrderItem.java, src/main/java/com/sparta/gamjaquick/payment/entity/Payment.java, src/main/java/com/sparta/gamjaquick/payment/repository/PaymentRepository.java
=> ⚒️chore: order fix
